# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
# 123

target 'UChat' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UChat

pod 'Firebase/Analytics'
pod 'Firebase/Auth'
pod 'Firebase/Firestore'

end
